services:
  module:
    image: strudel_notebook
    container_name: strudel_notebook

    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_SRC: node:25-bullseye
        #DOCKER_SRC: ubuntu:22.04

    stdin_open: true
    #tty: true
    network_mode: host
    #privileged: true
    
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR:-/tmp}/pulse/native
      - PULSE_COOKIE=/run/pulse/cookie
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-/tmp}
      - XDG_DATA_DIRS=${XDG_DATA_DIRS:-/usr/local/share:/usr/share}
      - SSH_AUTH_SOCK=/ssh-agent
   
      - GPU_PROFILE=${GPU_PROFILE:-nvidia-gpu}

    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [utility, compute, graphics]

    volumes:
      # - type: volume
      #   source: workdir
      #   target: /workdir
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.config/pulse/cookie:/run/pulse/cookie
      - ${XDG_RUNTIME_DIR:-/tmp}/pulse:${XDG_RUNTIME_DIR:-/tmp}/pulse
      - ${XDG_RUNTIME_DIR:-/tmp}/dconf:${XDG_RUNTIME_DIR:-/tmp}/dconf
      - ${SSH_AUTH_SOCK:-/dev/null}:/ssh-agent
      - ${HOME}/.gitconfig:/root/.gitconfig:ro

    command: ["/bin/bash", "-c", "tail -f /dev/null"]
    
# volumes:
#   workdir:
#   cache: